### ISSUE TITLE
channel overview - look

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#1]
redesign channel overview to look more like this:

16vhfxZCzEtSDCVu9RngG4NYoSydMZLE5w

![snap 2017-01-14 at 12 23 33](https://cloud.githubusercontent.com/assets/20817185/21954537/50dc8ad6-da54-11e6-9676-16f9fdcef824.png)

**Comment by dnelband** [comment]
done, placed the same image as there on default, should i put another image?

**Comment by haschimoto** [comment]
looks nice, its just missing the hover visual and link when you mouse over....

**Comment by haschimoto** [comment]
would also move

```
Created a month ago
davidbitnoyo
```

to the bottom of the square

**Comment by haschimoto** [comment]
and missing the "33 Channels" total info
