### ISSUE TITLE
metaheader channel list: add "-" between channels, add a dropdown at the very beginning that shows all channels

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#100]
Dropdown would start and replace the "My Subreddit" in this screenshot, but instead show a list with all channels with very small text font:
![snap 2018-02-07 at 11 26 10](https://user-images.githubusercontent.com/20817185/35911301-bb475eaa-0bf9-11e8-9b46-9e488e61e0e1.png)

**Comment by dnelband** [comment]
like this?

**Comment by haschimoto** [comment]
yeah, good for now!
