### ISSUE TITLE
comments are loading forever (FF on Windows7)

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#102]
![snap 2018-02-07 at 19 18 44](https://user-images.githubusercontent.com/20817185/35933730-bfeac63a-0c3b-11e8-9fed-53b145536006.png)

**Comment by dnelband** [comment]
sorry, i was working on another ticket when suddenly my battery charger died, i didn't see it. now its fixed

**Comment by haschimoto** [comment]
now works!
