### ISSUE TITLE
userheader: move "Unfollow/Follow" next to main logo

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#104]
![snap 2018-02-07 at 19 42 37](https://user-images.githubusercontent.com/20817185/35934898-1bb3637a-0c3f-11e8-96dc-eee3a7fde048.png)

**Comment by dnelband** [comment]
for following / unfollowing all topics. yes i see its not the best location for this now, maybe next to the logo? or just leave follow / unfollow to channels & topics

**Comment by haschimoto** [comment]
Lets try next to the logo.
