### ISSUE TITLE
Older Posts that had media now dont?

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#105]
e.g.:
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=topic+id=1DpPY5S6HpxsK6CQGWKZbKh9gVo1LnXze12

**Comment by haschimoto** [comment]
Actually almost all of here had nice images:
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=channel+id=1DpPY5S6HpxsK6CQGWKZbKh9gVo1LnXze11

**Comment by dnelband** [comment]
i've set a condition for every topic before a certain date (about 9 months or more ago, when we needed to change the file load mechanism) to search for files, it works different for new topics because the methode has changed.

**Comment by haschimoto** [comment]
good to see almost all back, some of the wallpapers even having 72 peers after 1 year! :)
