### ISSUE TITLE
Generated Avatars: Lets use first two letters

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#114]
Use this:
http://judelicio.us/initial.js/

and make it round and similar look like this:
https://ui-avatars.com/

**Comment by dnelband** [comment]
please check, is it better?

**Comment by haschimoto** [comment]
can you do "letters with colors" like in the example, but with first two letters even if its anon-cert:
http://judelicio.us/initial.js/

Just make sure it's all zeronet-self-contained.

**Comment by haschimoto** [comment]
lets keep current avatars and fix other more important stuff first...

**Comment by haschimoto** [comment]
@dnelband : Lets give this a try and use the first two letters of each username CERT.

**Comment by dnelband** [comment]
ready, is this what you meant?

**Comment by dnelband** [comment]
updated it to have constant bg colors by user name
