### ISSUE TITLE
Profile: "About" field not editable

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#119]
![snap 2018-02-23 at 21 38 56](https://user-images.githubusercontent.com/20817185/36615872-14e86298-18e2-11e8-8f6a-162946cde5eb.png)

**Comment by haschimoto** [comment]
also Avatar Image should be an "edit" or "remove" (aka "use autogenerated avatar") option right underneath the actual avatar in the right sidebar.

**Comment by haschimoto** [comment]
i still dont see the about field....

**Comment by dnelband** [comment]
does it still not show or is it ok?
