### ISSUE TITLE
DROPDOWN: selecting a channel from the dropdown doesnt load the channel, site stays white empty

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#122]

**Comment by dnelband** [comment]
i can't reproduce the issue, can you post a screen shot? firefox has a few strange issues with form elements and select tags, but on my computer selecting a channel leads to that channel page on all browsers, but on firefox it doesn't show the name in the select element itself, just white.

**Comment by haschimoto** [comment]
sure:
![snap 2018-03-05 at 15 03 12](https://user-images.githubusercontent.com/20817185/36978975-58adf92e-2086-11e8-8510-5517e0279ac4.png)

**Comment by dnelband** [comment]
what is the url? is it like this one: http://127.0.0.1:43110/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=channel+id=19jKEf7AHgrkPhWf71swMhFFZ52LXifVc4ch1
?

**Comment by haschimoto** [comment]
Of course not, how is this supposed to work on proxies or anywhere but
local if 127.0.0.1 is hardcoded :/

**Comment by dnelband** [comment]
i meant if its like   index.html?v=channel+id=CHANNEL_ID
the 127.0.0.1 is not hardcoded anywhere

**Comment by haschimoto** [comment]
it simply doesnt trigger any proper reload... i need to manually reload button in ff,,,

**Comment by dnelband** [comment]
btw are you using a proxy? this zero-pc?

**Comment by dnelband** [comment]
ok this seems to happen only in ff windows, i've updated a solution, does it fix the problem?

**Comment by haschimoto** [comment]
no, reloaded latest version 18 minutes ago

**Comment by haschimoto** [comment]
after updating zeronet itself to v3350, this now says ESCAPING IFRAME for a short time and then works?
![snap 2018-03-07 at 20 22 27](https://user-images.githubusercontent.com/20817185/37113306-4e788256-2245-11e8-9241-5f9558437ba0.png)

seems that ZeroVoat shouldnt do that in the first place and therefore it broke, but now seems fixed:
/Blog.ZeroNetwork.bit/?Post:127

still thats likely the cause that the dropdown algorithm tries to escape ZN...

**Comment by dnelband** [comment]
i've tested on 2 more windows clients but i couldn't reproduce that frame, indeed it was an issue with zeronet as well, still i would like to solve it so it wouldnt go to that frame, but as i said i couldn't reproduce it. does it open the link in a new tab on your client? does it behaves the same in chrome / explorer or is this only on firefox?

**Comment by haschimoto** [comment]
Ff, no new tab.
