### ISSUE TITLE
"unfollow" RSS for Zerovoat is placed messed up

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#123]
![snap 2018-03-02 at 18 46 37](https://user-images.githubusercontent.com/20817185/36913408-22913d44-1e4a-11e8-988d-9670af0237c6.png)

curious: why do those things started to happen?

**Comment by dnelband** [comment]
this is my mistake, i've changed the css of the item on the mid-size layout but have'nt notice the full screen layout
