### ISSUE TITLE
NEW TOPIC Button: NOT WORKING!

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#126]
WT??? Why does this link not to a new topic that is related to the CHANNEL I want to add a topic????

IT LINKS TO MY USER ADRESS:
http://zero-pc:43110/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=user-admin+s=new-topic+id=MYUSERID

**Comment by dnelband** [comment]
where does this happen? when i click on NEW TOPIC it links to the new topic form with the related channel selected.

**Comment by dnelband** [comment]
is this still happening? i don't understand the issue in this ticket
