### ISSUE TITLE
Add new Topic: Do not allow this from PROFILE, remove the channel DROPDOWN, HARDCODE ADD TOPIC to Channel where button got pressed

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#127]
ALL to avoid stupid entries, empty stuff, breakage and general mismatch like these:
![snap 2018-03-05 at 14 58 00](https://user-images.githubusercontent.com/20817185/36978802-cd88d5e4-2085-11e8-9c85-4f63aedc640a.png)

**Comment by dnelband** [comment]
the channel dropdown is disabled (is this ok or should it just show the channel name as text?) but what do you mean "do not allow from profile"? i've removed all of the "new topic" buttons from the user profile already before, it's only possible from a channel-view.

**Comment by haschimoto** [comment]
Remove the dropdown, yes.
