### ISSUE TITLE
No topic edit/delete button

### ISSUE THREAD

**Issue by slrslr** [zer0net/zerovoat#131]
Hello, i see i can administrate (edit) my topics [here](http://127.0.0.1:43110/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=user-admin+s=topics), but i think it is needed the edit button or link is also on the topic page, not hidden under tiny icon in the top right corner.

Edit and delete button.

**Comment by leftside2** [comment]
I agree. 👍

**Comment by dnelband** [comment]
delete topic option added + topic edit toolbar (edit / toggle / delete) will now be visible on topic view, topic list & user admin

**Comment by slrslr** [comment]
This is great i see the topic was deleted.

The cosmetic thing about the delete button is that when i view the topic and move the mouse cursor to the delete "button", the mouse cursor does not change to a clickable cursor (like there is no hyperlink) and after clicking, the user is not redirected to the channel index.

**Comment by dnelband** [comment]
done, please test again

**Comment by slrslr** [comment]
@dnelband when i am on the [page that lists my questions](http://127.0.0.1:43110/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=user-admin+s=topics) and move the mouse cursor over the delete "button", the cursor change from arrow to the hand to acknowledge there is a hyperlink. But when i am on a question/topic page, then the button do not change mouse cursor and do not appear clickable and after clicking i keep being on the topic instead of redirecting to the channel index. I do not see it as a problem, just a cosmetic thing. Most important is there is option to remove topic/question. By the way, it may be handy if there is a prompt for a confirmation before deleting topic: "Are You sure you want to delete this question/topic?"

**Comment by dnelband** [comment]
@slrslr is it behaving properly now? can we close the ticket?

**Comment by slrslr** [comment]
@dnelband Hi, i created new topic with image, then i posted two comments with other files (audio and video), then being inside a topic, i hit Delete button to delete the topic. It deleted it, but all three files remains in my user's directory even i did "Recheck files" on ZeroHello menu next to Zerovoat site and its merger.

**Comment by dnelband** [comment]
hi @slrslr , it wasnt supposed to do what you wrote, but that is a good point. now on topic delete all files (topic files & comment files) are deleted from user directory, and all file entries & comments are removed from the user data.json . please test & let me know

**Comment by slrslr** [comment]
@dnelband yes, it worked. Thank you, for adjusting it, it is nice.

**Comment by slrslr** [comment]
@dnelband Edit, Delete button no longer visible in my topics

**Comment by dnelband** [comment]
@haschimoto
