### ISSUE TITLE
Can not delete the file i uploaded to my topic/question

### ISSUE THREAD

**Issue by slrslr** [zer0net/zerovoat#132]
Hello, when editing my question/topic/comment, i can not find the button to delete the file i uploaded as its attachment.

**Comment by dnelband** [comment]
added file delete option, please test now

**Comment by slrslr** [comment]
thank You @dnelband , i tried to edit my existing comment that conains an image and also tried to add new comment with new image, but when i try to edit it i see i can edit only text. Do not see way to remove image.

**Comment by dnelband** [comment]
hi @slrslr , added comment file edit support, please test

**Comment by slrslr** [comment]
@dnelband i tried to post a comment that contained a image. And clicked button to post it. Now it says "Posting Comment".

Firefox console:
Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.
react-dom.js:18238:8
TypeError: this.props.onCommentPosted is not a function[Learn More] all.js:5470:47
hideProgress all.js:595:7
[ZeroChat] Unknown request 
Object { tasks: 0, size_limit: 10, address: "1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb", next_size_limit: 10, auth_address: "1JNHWo2k8sG6mZ3T1Lgzpsbf5B4fSH4pyH", feed_follow_num: 12, event: […], content: {…}, peers: 312, auth_key: "removedbyme", … }
class.js:20:7

But when i refresh page, i see it was posted. When i then hit delete button on image, it do nothing (except saying it can not sign some image i uploaded long time ago), after refresh, i no longer see the image.  I do not know where is the zerovoat folder, i can not find it so i can not verify if file was realy removed.

**Comment by dnelband** [comment]
if you have an error notice that specifies that it cannot sign a file within your user directory you should remove because it can probably cause problems

**Comment by slrslr** [comment]
@dnelband > you should remove

Please can you suggest from where i remove it, i know where is my zeronet data folder, but can not find my files in ZeroNet\data\1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb and its sub-folders

**Comment by dnelband** [comment]
we are using merger_sites for zerovoat, look in
ZeroNet/data/19gtNiKNZMq6nTdWThGCQQAS2bCYAY1tFh/data/users/USERID

**Comment by slrslr** [comment]
@dnelband not sure if that is only merger zite that is used, because when i watch my user folder (ZeroNet/data/19gtNiKNZMq6nTdWThGCQQAS2bCYAY1tFh/data/users/USERID) where i have couple of images (including mentioned file that could not be signed) i uploaded new image as a comment attachment, but this .jpg file was not added to this user folder of mine (i refresh folder) and it is not on site. This i see when i upload image:

Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.
react-dom.js:18238:8
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:43110/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/undefined. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
hideProgress
all.js:595:7
[ZeroChat] Unknown request 
Object { tasks: 0, size_limit: 10, address: "1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb", next_size_limit: 10, auth_address: "1JNHWo2k8sG6mZ3T1Lgzpsbf5B4fSH4pyH", feed_follow_num: 12, content: {…}, peers: 281, auth_key: "removedbyme", settings: {…}, … }
class.js:20:7
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the CommentListItem component.
react-dom.js:18238:8
TypeError: res is null[Learn More]
all.js:1187:15
hideProgress
all.js:595:7
[ZeroChat] Unknown request 
Object { tasks: 0, size_limit: 10, address: "1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb", next_size_limit: 10, auth_address: "1JNHWo2k8sG6mZ3T1Lgzpsbf5B4fSH4pyH", feed_follow_num: 12, content: {…}, peers: 281, auth_key: "removedbyme", settings: {…}, … }
class.js:20:7

..........The site says it delay publishing for 29 seconds. And instea dof image is questionmark. Then on page i see 404 black image.

.......... When i click to delete image, i see:

Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.
react-dom.js:18238:8
TypeError: res is null[Learn More] all.js:1187:15
TypeError: res is null[Learn More] all.js:1187:15

on page reload, 404 image or questionmark image is no longer on page.

**Comment by dnelband** [comment]
hi @slrslr , i was able to reproduce the problem & fixed it on my local. please test again by: commenting with an image etc', edit comment, delete image, upload another

**Comment by slrslr** [comment]
I posted a comment with a text and a image into a topic, it was successful, shows 1 peers and image is in my user directory. When i click delete button, it says content was published to 5/5 peers. But page is not reloaded, image is still visible. i check dev. console of the firefox: https://defuse.ca/b/Q9F0N4FxxGyftUxjTO68aB (password: zv)
After page refresh, i see that the image is still in the user directory but no longer visible on zite...
I tried to "Check files" and "update" command on zerohello, next to the zite and merger zite, but it not removed file from my user directory. Though Zerovoat on zerohello says "121 file update failed", but i think someone said that this is normal, cause by other users files being out of sync/renamed or something.

**Comment by slrslr** [comment]
@dnelband i forgot to mention you in my previous comment, thank you

**Comment by dnelband** [comment]
thanks @slrslr , caught the error & fixed it, please update & test

**Comment by slrslr** [comment]
@dnelband it is nice, comment editting, image upload and image delete from a comment works (and file is removed from user's directory),

BUT when i add image to a topic (not comment), image is added, and when i click delete button, nothing happen until i refresh page, then i see image is not on page, but it remains in user's directory.

**Comment by dnelband** [comment]
hi @slrslr , please update & test, but i'm not sure that my sign & publish works now, do you see an update for zerovoat from the last minutes?

**Comment by slrslr** [comment]
@dnelband no, your sign & publish probably not worked, i see no change, file was not deleted from my user dir. And ZeroHello says the zite was updated one hour ago.

**Comment by dnelband** [comment]
Hi @slrslr , just tested on another client and it works, please test again

**Comment by slrslr** [comment]
@dnelband 
thank you, attaching and deleting image from topic and comment works good, also file is removed from user's directory. Thank you for fixing it.
