### ISSUE TITLE
Editting comment does not work

### ISSUE THREAD

**Issue by slrslr** [zer0net/zerovoat#133]
Hello, i apologize if you already know about this issue.

When i edit topic, it works, but when i edit comment, it redirect me to the site index and when i return back i see comment was not modified.

The Firefox developer console (F12) says:
Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.
react-dom.js:18238:8

**Comment by dnelband** [comment]
fixed, please test now

**Comment by slrslr** [comment]
Thank you, it (comment editing) works. :)
