### ISSUE TITLE
Edited comment does not keep line breaks

### ISSUE THREAD

**Issue by slrslr** [zer0net/zerovoat#134]
Hello,

after i edited my comment, i seen that comment editing text area has line breaks (empty lines), but resulting comment that is visible on discussion/front end is one paragraph without formatting (line breaks/empty lines).

It would be handy if it reflect empty lines that i made during editing. When editing whole discussion topic, it saves empty lines, but comments not. Which makes a mess and hard to read comments.

**Comment by dnelband** [comment]
currently we do not plan on edited comments to have html content because we want to keep it simple, you can add this as a suggestion for the next version
