### ISSUE TITLE
replace main loading spinning icon

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#139]
replace main spinning circle when loading with spinner from here:
https://hooktube.com
![snap 2018-03-27 at 15 43 24](https://user-images.githubusercontent.com/20817185/37971221-b05c94fe-31d5-11e8-822a-735f24928062.png)

**Comment by haschimoto** [comment]
https://worldchess.com/berlin

**Comment by dnelband** [comment]
http://tobiasahlin.com/spinkit/

**Comment by haschimoto** [comment]
The other spinner is different, lets try to rip one of those.

**Comment by dnelband** [comment]
ready, is it good?
