### ISSUE TITLE
broken avatar on user zrunner@zeroid.bit

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#140]
last comment on this thread:
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=topic+id=1AWwhg4EiWAVttfQboJZ4wJfX3WawfJT3h4

**Comment by dnelband** [comment]
1 - added a fallback option when there is an error on image loading
2 - but it seems the error load came from a missing cluster info, i've added a fallback function to search for the directory in case it doesnt have the cluster_id via the json_id of the file. anyway it loads now
