### ISSUE TITLE
No topics anymore

### ISSUE THREAD

**Issue by slrslr** [zer0net/zerovoat#142]
I can see no topics since today at ZeroVoat http://127.0.0.1:43110/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb
Can i fix it anyhow?

**Comment by dnelband** [comment]
hi @slrslr , try to reload / rebuild db?

**Comment by haschimoto** [comment]
any way to not force everyone to rebuild the DB?
I doubt people will do that, they just think its broken and simply leave...

**Comment by haschimoto** [comment]
to test:
https://www.zerogate.tk/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/

**Comment by dnelband** [comment]
hi @slrslr , please test now, the issue is fixed at least on zerogate.tk

**Comment by slrslr** [comment]
Hi, i have reloaded db (quit zeronet, renamed zeronet/data/content.db, start zeronet), it took 2 hours and then zerovoat started working. Zeronet maintainer is aware about this issue, i sent them this info. Maybe this issue can be closed, i am unsure if ZeroVoat can do anything about this.
BTW: i realized that possible cause of this db corruption can be my computer frozen/got reseted.

**Comment by haschimoto** [comment]
Happened to my computer as well, also that proxy, so it seems like a real
issue, and only zerovoat noticeable having to do this reload db to make it
work.
