### ISSUE TITLE
"Topic" created without any channel?

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#143]
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=topic+id=1NxN5b7ZTmnfPwcLFhBRjPAqcuwbxrEfEBtopic1

**Comment by haschimoto** [comment]
any idea how this is possible?

**Comment by dnelband** [comment]
all i see is "no topic found", where did you see this? which page i mean

**Comment by dnelband** [comment]
when it was still possible to select a channel from a dropdown

**Comment by haschimoto** [comment]
Latest topic of all topics.

**Comment by dnelband** [comment]
the last topic i see is "another test topic"

**Comment by haschimoto** [comment]
last topic is this:
![snap 2018-03-29 at 17 54 29](https://user-images.githubusercontent.com/20817185/38099198-4b5d6bf4-337a-11e8-9b55-1466de2928b7.png)

**Comment by haschimoto** [comment]
whats also odd is that zerovoat on tk is also not updated, it is missing the second comment:
https://www.zerogate.tk/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=topic+id=1DnmGgRaHo2puhutf6Dn4MjF4eXmqmdLZ1topic5

I do see the second comment on thsi topic here locally...

**Comment by haschimoto** [comment]
so both you and zerotk is not automatically updating to latest DB?

**Comment by dnelband** [comment]
well on zerotk when i wanted to test something it took about 10 times refresh / several clicks on "update" to show changes but im sure its connected to the db updates. on my local it usually shows immediately, when i tested on other clients. when i see that topic i'll fix the issue, cause im not sure how it happend now

**Comment by dnelband** [comment]
i still dont see that topic, i see all the new ones after "another test topic" but not that one
