### ISSUE TITLE
Topic loading for some topics seems stuck, not sure why

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#147]
e.g.:
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=topic+id=1PniNzyi8fygvwyBaLpA9oBDVWZ5fXuJUw2

It is first topic on this page here:
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=channel+id=1PniNzyi8fygvwyBaLpA9oBDVWZ5fXuJUw1+sb=new+p=2

**Comment by dnelband** [comment]
fixed
