### ISSUE TITLE
Topic doesnt load

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#152]
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=topic+id=1L5rGDgTs4W2V7gekSvJNhKa7XaHkVwotDtopic8

**Comment by dnelband** [comment]
this is what i see
![screen shot 2018-03-29 at 18 48 56](https://user-images.githubusercontent.com/5212537/38101877-e2399f28-3381-11e8-8241-e2e2dc61a970.png)

**Comment by haschimoto** [comment]
it is 10th topic "Bla Bla Bla" from here:
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=channel+id=1R67TfYzNkCnh89EFfGmXn5LMb4hXaMRQ3

**Comment by haschimoto** [comment]
hmm, now it loads here too fine...
needed to click at least 5 times on it, as it was stuck on "Loading Zite" with new spinner

**Comment by dnelband** [comment]
ah ok, it happens to me sometimes that the loading zite screen take a lot more then usual, but i see no error on console and usually cant reproduce so i thinks its just a timeout with zeronet api if it does something in the background, but im not sure. anyway i'll try to find an answer as to why this happens, but if its "loading zite" and not "loading topic" its not a problem with the topic

**Comment by haschimoto** [comment]
yeah, its "loading zite" that then hangs...
Ill close for now.
