### ISSUE TITLE
Channel: Align "Channel name" to topics list

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#154]
![snap 2018-03-29 at 19 06 13](https://user-images.githubusercontent.com/20817185/38102813-a84ea08a-3384-11e8-81d0-baa14a0084ab.png)

**Comment by dnelband** [comment]
i think your viewing the site on a really big screen, this is how it looks on my screen when its full width:
![screen shot 2018-04-03 at 14 08 51](https://user-images.githubusercontent.com/5212537/38248437-a40af72c-3748-11e8-81a5-c3d70d0a1dbb.png)
if i'll align it with the topics it will go over the logo, unless you have a really big screen or zoom out a lot
