### ISSUE TITLE
Topic / Comment: Prevent auto-loading EXTERNAL embedded files (like videos or images) without a consented click on it

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#155]
e.g. this topic has an external image embedded inside the comment text area:
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=topic+id=1E6q3J9comogQMX5nMUkgN4scofBy1NPuJtopic35

/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=topic+id=1E6q3J9comogQMX5nMUkgN4scofBy1NPuJtopic30

Todo:
- do not automatically load ANY external media files (like images or videos) outside of ZN
- either just show the link without loading it and if a user clicks on it, it does load and extend the area to show it 
or 
- put a "EXTERNAL MEDIA, LOAD ANYWAY?" warning overlay on top of it, that only if clicked loads and shows the media.

I would prefer the "shield" solution though to make it more obvious if someone links any image or video content from clearnet, see this solution already in place:
https://github.com/zer0net/zerovoat/issues/93

**Comment by haschimoto** [comment]
compare voat:
https://voat.co/v/pizzagate/2471555

embedded video in first comment not opened default:
![snap 2018-03-29 at 19 33 13](https://user-images.githubusercontent.com/20817185/38103960-1bfb0c5a-3388-11e8-83f6-976fe4fa49bf.png)


opened by default:
![snap 2018-03-29 at 19 33 47](https://user-images.githubusercontent.com/20817185/38103978-27e2049c-3388-11e8-8ec7-806d0430bf08.png)

**Comment by haschimoto** [comment]
i would prefer the "shield" solution though to make it more obvious if someone links any image or video content from clearnet, see this solution already in place:
https://github.com/zer0net/zerovoat/issues/93

**Comment by dnelband** [comment]
im currently working on this but its requires a bit of a complicated solution so it will take me a little bit more time

**Comment by dnelband** [comment]
implemented the shield solution, but it currently search the content raw html before rendering for any tags that fit , so it means i will have to add "cases" with time to cover all of the possibilites / tags in which external media would be embeded. i.e a period of QA is necessary to cover all cases.
is this what you meant? should the shield be bigger / smaller?

**Comment by dnelband** [comment]
here is a good showcase of the change : 
http://127.0.0.1:43110/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=topic+id=1E6q3J9comogQMX5nMUkgN4scofBy1NPuJtopic30

**Comment by dnelband** [comment]
btw its impossible to post media in comments because it doesnt support html tags. we can change it if you want, but you said at some point that you prefer to keep it simple

**Comment by haschimoto** [comment]
How is that nice example working before?
That example is great solution already!
Now would it be possible to show the information about what is linked?
Like it is on Zerovoat, where you show the exact link to the ITEM as text, so you know what will open from where without it being a total blackbox?

**Comment by dnelband** [comment]
yeah its possible to show information, what would you like to show? should i paste the code of an image for example as text as a form of preview?

**Comment by haschimoto** [comment]
The URL

**Comment by dnelband** [comment]
done

**Comment by haschimoto** [comment]
How about doing it more subtle like in above voat examples?
So it is not a big black box, but only the link and a warning text behind or below it that clicking loads a CLEARNET SOURCE?
