### ISSUE TITLE
"Add File": Any "added file" from ZV should be stored on an IFS Cluster instead of a ZeroVoat Cluster

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#156]
Any ZN content should go to a IFS Clusters merger sites and not ZV Clusters, so it can be easily re-used.

**Comment by haschimoto** [comment]
So e.g. this file:
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/merged-CDN/19gtNiKNZMq6nTdWThGCQQAS2bCYAY1tFh/data/users/1DnmGgRaHo2puhutf6Dn4MjF4eXmqmdLZ1/krusty14_gif.jpg

should be on any IFS cluster instead and linked back:
- /15fDN4wasXuyS8krtKvrxEVmWWLz6Qh518/
- /1MzV32sv55VSD5Vr7u3mcMPsX2oG9PHusr/

or another third IFS-compatible cluster specifically for ZV, that does hsow then all "added files" on IFS frontend as well.

**Comment by dnelband** [comment]
all of the cluster are cdn and are compatible with each other, i.e also items from ZV cluster could be used on IFS, but do you want that items with files created on ZV will automatically be posted on IFS?

**Comment by haschimoto** [comment]
Yes, thats the idea.
Store all content other than specific comments, votes, etc. on IFS
clusters, so they show up there...

**Comment by dnelband** [comment]
but they can show up in IFS also now. weather something appears on IFS or not is depending on the DB Entry. i.e to make the uploaded files appear in IFS as items we need just to create a DB entry for item for that file. in light of this, do you still want all files to be stored only in IFS clusters, or does this make it unnecessary?

**Comment by dnelband** [comment]
ok, understood, im on it

**Comment by haschimoto** [comment]
Hmm, but how does it work though on IFS side?
That a ZV user gets a channel with his certificate and can edit content
from ZV on IFS frontend?
Or is it specially marked ZV and we need to make editing content on ZV
possible?

Maybe lets think this through first :)

**Comment by dnelband** [comment]
Yeah thats a good point, we will habe to create an IFS channel for the user
if he doesn’t have one in order to show the item on IFS & to be able to
edit it. But editing content from ZV to IFS is not a problem, both options
are doable
