### ISSUE TITLE
New Topic: Embed URL: change text to "Embed URL from IFS", link "IFS" word to popup in new window/tab IFS ZN Zite

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#158]
also check if its really IFS URL, reject any other URL

![snap 2018-04-03 at 14 50 29](https://user-images.githubusercontent.com/20817185/38250253-93a451a2-374e-11e8-9e3f-b7ba9fe05918.png)

**Comment by dnelband** [comment]
1 - unfortunately ZN blocks a new tab / new window link (it just shows a white page with an error)
2 - added a normal link + added a rule for restricting embed urls, but it needs to be more refined, right now its just "embed url must start with merged-CDN" but it needs to be merged-CDN/CLUSTER/data/users/USER/FILENAME
