### ISSUE TITLE
Comments: show correct Text Formatting (like spacing and linebreaks), that are visible and saved while editing a comment but not correctly recognized when shown in saved mode

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#160]
It works for Topics, but (no longer?) for comments:
E.g.:
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=topic+id=1DnmGgRaHo2puhutf6Dn4MjF4eXmqmdLZ1topic8

**Comment by haschimoto** [comment]
this is also pretty important... suggesting to proceed with ZV2.1 here instead of IFS...

**Comment by dnelband** [comment]
done, but we didnt have it until now because you wanted to keep the comments simple, so we didnt add a text editor to the comments

**Comment by haschimoto** [comment]
well, linebreaks and spaces shoulöd always be saved, there is no need for a fancy editor... it just common sense if i add a linebreak with "Enter" it should not ignore that, thats since forever the internet didnt even have fancy editors, but black and green screens...

**Comment by haschimoto** [comment]
NOTE:
what is even weirder is editing a comment from the Profile Page brings back the correct formatting EVEN WITHOUT A FANCY EDITOR:
![snap 2018-05-09 at 23 07 44](https://user-images.githubusercontent.com/20817185/39839903-f688ff1a-53dd-11e8-86c0-eebf1816087a.png)
vs editing mode:
![snap 2018-05-09 at 23 09 01](https://user-images.githubusercontent.com/20817185/39839941-0bb958f8-53de-11e8-8b48-4926959f804e.png)

So the formatting IS SAVED, just not correctly SHOWN?

**Comment by haschimoto** [comment]
so compared to reddit, we dont need the COMPLEX editor, just make sure that comments are SHOWN WHEN SAVED the same when edited again with just a comment field:
![snap 2018-05-09 at 23 12 42](https://user-images.githubusercontent.com/20817185/39840121-9a44f5dc-53de-11e8-8354-7c969efa35f7.png)
