### ISSUE TITLE
External sources: Mini-Preview in Listview: Prevent external media from autoloading and shown as minipreview

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#167]
Topic:
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=topic+id=1PiXrhT1UjMZmJc5WFhfUxourdfapeHJ8otopic19

media is loaded as minipreview in LIST:
![snap 2018-05-18 at 19 18 07](https://user-images.githubusercontent.com/20817185/40248432-3c4dbb8c-5ad0-11e8-9dab-a673c84be2ea.png)

Also media is loaded in minipreview in the topic itself:
![snap 2018-05-18 at 19 16 57](https://user-images.githubusercontent.com/20817185/40248392-0f6865cc-5ad0-11e8-9e18-e08ef02b5a81.png)

**Comment by haschimoto** [comment]
two small things:
- show link URL below the blackbox screen
- do not autoload the minipreview, as it is still shown in the small picture:
![snap 2018-08-06 at 21 48 08](https://user-images.githubusercontent.com/20817185/43737732-8d3478f2-99c2-11e8-97d2-d5452857f5e3.png)

**Comment by dnelband** [comment]
what should appear instead of the embeded link in the list view? should it only be loaded on topic view?

**Comment by haschimoto** [comment]
Minipreview: Videos are not EXTERNAL, so should still show the video logo instead of external:
![snap 2018-08-07 at 15 48 47](https://user-images.githubusercontent.com/20817185/43779809-886c6d4c-9a59-11e8-9a1c-4f0b96170b38.png)
