### ISSUE TITLE
new user account: adding 2 comments and 1 vote will show 3 comments under my account, when only 2 comments should be correct

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#172]
![snap 2018-08-04 at 11 53 44](https://user-images.githubusercontent.com/20817185/43675010-10d867dc-97dd-11e8-8ba3-3d974112366a.png)

**Comment by haschimoto** [comment]
could be also the count is simply wrong, so it shows comments+1, that is always 1 more comment than actually exist.

**Comment by haschimoto** [comment]
i now have 3 comments and it reads "5 comments".
But it doesnt display any comments of comments, that is anything that is not a comment of an original post.
So my new guess is that it does simply not show any comment that is not a direct comment of a post, but e.g. a comment of a comment, so it is nested?

**Comment by dnelband** [comment]
yes, your guess is correct, i've double checked it with my two users. what should i do? just display all the comments regardless of nesting as root comment? maybe i can add another info line "in response to comment [comment id] on topic [topic id] with a link?
