### ISSUE TITLE
embedded video: green bars incorrect (likely related to IFS or wrong piecemap chunk count)

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#178]
e.g.
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=topic+id=1DnmGgRaHo2puhutf6Dn4MjF4eXmqmdLZ1topic2

embedded video is shown all green bars, but is really only 13 chunks and stops at 0:42 min:
![snap 2018-08-07 at 16 07 35](https://user-images.githubusercontent.com/20817185/43781028-46b7335c-9a5c-11e8-844c-73084a88cd8c.png)

**Comment by haschimoto** [comment]
happens also for the same video on IFS:
/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?view:item+id:2_1MEqso53FzGtN3NRYPuDBBbNbP2tUFiR82_item_10+type:video

note the missing download button, so it is not fully downloaded.

**Comment by haschimoto** [comment]
i manually deleted the file and piecemap, will report back.

**Comment by dnelband** [comment]
the file i see has 75% loaded and the same amount of green bars

**Comment by dnelband** [comment]
did the problem reproduce now that you deleted
