### ISSUE TITLE
Missing comments: Topic says it has "6 comments", but shows only 5 (ask Tamas about missing @zv.anonymous comments)

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#38]
https://bit.surf:43110/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?view:topic+topic_id=15AraqYEEUD2fcP4byP3oEH4TMBRe1uQrx1

**Comment by haschimoto** [comment]
the images normally shown in the reply called "also in a reply" ALWAYS takes 30-60 seconds to load the image even after refresh?
![snap 2017-06-21 at 23 12 40](https://user-images.githubusercontent.com/20817185/27407022-257c7c2a-56d7-11e7-9a9f-6c0309935dbb.png)

**Comment by haschimoto** [comment]
Lets ask Tamas about what might be the cause for not seeing zv.anonymous content.

**Comment by haschimoto** [comment]
@dnelband : just curious: have you send an email yet to Tamas about why the anonymous comments might not be pusblished correctly?

**Comment by dnelband** [comment]
i was just writing it now, sent it to you as cc

**Comment by dnelband** [comment]
some comments are replies to other comments which are missing from the peer due to the zv.anon issue, so the topic counts all comments in local db that belong to him, but those who are replies to missing comments arent shown because they're parent is missing
