### ISSUE TITLE
BUG: 3x same topic entries

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#39]
on pagination-5 one can see 3xtimes the same topic:
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?view:main+page=5+sort=-added
![snap 2017-06-21 at 22 26 54](https://user-images.githubusercontent.com/20817185/27405173-d88e99bc-56d0-11e7-87ed-ab21b23dc1ea.png)

**Comment by dnelband** [comment]
yeah it was a duplicate, got created 3 times, the error was fixed long ago but the three entries remained. i removed it

**Comment by haschimoto** [comment]
it is NOT fixed on my local... not sure why, but i see still 3xtimes topic

**Comment by dnelband** [comment]
i brought it back cause you ask not to remove

**Comment by haschimoto** [comment]
That was a different ticket??
