### ISSUE TITLE
broken images

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#40]
are those still on the server? or on the cluster?

i have loaded them in the past and they worked fine, like e.g.:
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?view:topic+topic_id=1DobcNU81BZrQViu9L6uUu7qcC4Afd9r962

**Comment by dnelband** [comment]
i dont see the topic at all, is it yours?

**Comment by dnelband** [comment]
i see it local with the image, but i dont see it on bit.surf

**Comment by haschimoto** [comment]
i dont see it local here, any way to fix it on bitsurf? can you check the file is on ZVS CLUSTER?

**Comment by haschimoto** [comment]
i think the files are still not distributed at least 1xtime over the new ZV cluster and therefore appear BROKEN:
http://zero-pc:43110/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?view:topic+topic_id=13AvYD3hX888Ey6y8kFEce3Ak8hVNLcdrg1

e.g. broken:
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/merged-CDN/19gtNiKNZMq6nTdWThGCQQAS2bCYAY1tFh/data/users/13AvYD3hX888Ey6y8kFEce3Ak8hVNLcdrg/escalator-jpg.jpg

not broken without merged CDN:
http://zero-pc:43110/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/data/users/13AvYD3hX888Ey6y8kFEce3Ak8hVNLcdrg/escalator-jpg.jpg

**Comment by haschimoto** [comment]
@dnelband : please check again at your local install if the file appears correct, then please keep your machine ON and SEEDING to at least bitsurf until 2+ peers have it
