### ISSUE TITLE
missing media (image or video): add generic PLACEHOLDER for all EXPECTED files, then if it cannot be loaded after a while, show a "404 missing" placeholder instead of broken IMG

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#41]
I recall there was a video in one of the REPLY comments here:
https://bit.surf:43110/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?view:topic+topic_id=1GAWwPWreQXo1CwcefCgL6w5wYPkNFWbsj1

How about we clearly add PLACEHOLDERS for any item that should be there, but is not loaded right now?
So we clearly see where should be an item or not.
It sometimes happens that if you wait long enough, an item SUDDENLY POPS IN and starts to display, but that is not a good behaviour imo.

**Comment by haschimoto** [comment]
seems also missing:
https://bit.surf:43110/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?view:topic+topic_id=1HFE38masGtTm8Rj5qtNV49sHP7Xfm3ZB51

**Comment by dnelband** [comment]
first topic - there was a bug with comment & media files loading, now its there, second topic - pic was removed, the topic was a test, ill remove it

**Comment by haschimoto** [comment]
Please do NOT renove this topic!
All is a test by now and this is a VALUEABLE one!

**Comment by haschimoto** [comment]
You didnt seem to add any PLACEHOLDERS at all?
The idea is to ADD PLACEHOLDERS, so we know in advance where things are supposed to have MEDIA, WHICH FOR VARIOUS REASONS could not be loading (being offline, etc.).

So when surfing here:
https://bit.surf:43110/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?view:channel+channel_id=1DpPY5S6HpxsK6CQGWKZbKh9gVo1LnXze11

INSTEAD of slowly loading any images or media type previews, there should be a small tiny PLACEHOLDER image immediately which then is replaced by an actual img if loaded.

So instead of this:
![snap 2017-06-22 at 19 39 36](https://user-images.githubusercontent.com/20817185/27447759-921d3ab2-5782-11e7-8f33-89ee5c56594c.png)
and then after a while this:
![snap 2017-06-22 at 19 34 28](https://user-images.githubusercontent.com/20817185/27447767-98cb5498-5782-11e7-8d59-ce40bc686c0a.png)

we immediately see a placeholder in the 3 white spots, even if the imgs doesnt load and show be broken or missing after a while.

**Comment by haschimoto** [comment]
Lets also show this PLACEHOLDER inside a topic or comment, e.g. here:
https://bit.surf:43110/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?view:topic+topic_id=1NZ4LvZqg61LxtRfEr5Y46KRhYCzWRnqck1

So even if the img is TEMP gone for whatever reason (it could be it will be online again after a while), we display a generic PLACEHOLDER IMMEDIATELY, then if we get the INFO MISSING/BROKEN, we show a MISSING 404 IMG instead (similar to the missing IFS img "Ive seen things..."

It also should prevent showing a huge broken img like this then after a while like this:
![snap 2017-06-22 at 19 45 42](https://user-images.githubusercontent.com/20817185/27448015-7339b5f2-5783-11e7-8cc1-1e7901bab1f2.png)
