### ISSUE TITLE
ZV Cluster: change DB name from "ifs_cluster.db" to a more generic name, e.g. universal_cluster.db?

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#45]
![snap 2017-06-22 at 19 03 28](https://user-images.githubusercontent.com/20817185/27446577-583ae186-577e-11e7-8b34-08ea1af58d4e.png)

assuming the DB schemata are the same for ifs clusters and zv clusters, we could rename all of them to universal_cluster.db name?

Then we have to rename them all the same, also on the two IFS Clusters?

**Comment by dnelband** [comment]
since it isnt important for anything but the clusters internal use, can we close this?
