### ISSUE TITLE
Browsing a Channel: add - /Channelname to ZeroVerse browser title? e.g. "ZeroVerse - /Wallpapers"

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#47]
https://bit.surf:43110/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?view:channel+channel_id=1DpPY5S6HpxsK6CQGWKZbKh9gVo1LnXze11

**Comment by dnelband** [comment]
since the site is inside an iFrame shell of zeronet its not possible to manipulate anything outside the iFrame (ZeroNet dragbar, browser info etc')

**Comment by haschimoto** [comment]
thats really sad :)
maybe Tamas could built that one exemption for browser title...
