### ISSUE TITLE
Missing Channels (spinner shows forever without loading)

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#48]
eg 
- ZeroNet:
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?view:channel+channel_id=1R67TfYzNkCnh89EFfGmXn5LMb4hXaMRQ2

- Politics:
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?view:channel+channel_id=1R67TfYzNkCnh89EFfGmXn5LMb4hXaMRQ1

**Comment by haschimoto** [comment]
also, this topic has no channel when clicked:
https://0netproxy.ml/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?view:topic+topic_id=15Mcf8JqSwTrKWZ6qj68mmaAvQx1F9rqUZ1

**Comment by dnelband** [comment]
both are channels that belong to your user which content was lost in the migration process
