### ISSUE TITLE
missing media (list)

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#50]
- https://0netproxy.ml/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?view:topic+topic_id=1A5Uw4pejzgKx4c3yZkz8whBcqMaypp1Wo1

- https://0netproxy.ml/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?view:topic+topic_id=1DpPY5S6HpxsK6CQGWKZbKh9gVo1LnXze13

-

**Comment by dnelband** [comment]
i dont have both of these files anywhere, also not in cache
