### ISSUE TITLE
missing comments (list)

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#52]
says it has 2 comments, but none show:
- https://bit.surf:43110/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?view:topic+topic_id=1

**Comment by dnelband** [comment]
both of these comments are replies to my comments (davidnelband@zeroid.bit) which you wanted me to delete, so allthough the comments belong to the topic, and thus get counted, but their parent comments are missing so they are not loaded

**Comment by haschimoto** [comment]
This was before you deleted them. Anyway, lets close this then.
