### ISSUE TITLE
Channellist: missing sorting, default sort should be number of topics

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#57]
https://bit.surf:43110/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?view:channels

**Comment by dnelband** [comment]
i would suggest also to place the channel sort above the list because it could be covered by the user menu if username is long

**Comment by haschimoto** [comment]
rename "Last Topic" sort-option to "Last activity"
