### ISSUE TITLE
DOGE: restore this post

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#58]
this seems like an archive:

https://zeronet.korso.win/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/topic.html?topic_id=1DobcNU81BZrQViu9L6uUu7qcC4Afd9r962

**Comment by dnelband** [comment]
https://0netproxy.ml/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?view:topic+topic_id=1DobcNU81BZrQViu9L6uUu7qcC4Afd9r962

**Comment by haschimoto** [comment]
thanks!
