### ISSUE TITLE
ZV-Test frontend & cluster

### ISSUE THREAD

**Issue by dnelband** [zer0net/zerovoat#62]
site - http://127.0.0.1:43110/17Vt4aFGwYucUwzUFVCAMkU8QBFkdrSehc
cluster - http://127.0.0.1:43110/1PkiDgB5Eg2Ky1bdnDujcMASKWLyeoVn4b

merger name - CDNTEST (to avoid littering)

**Comment by haschimoto** [comment]
Unusable SLOW, i mean it takes 2-3 minutes if i click anywhere with so few content...

**Comment by haschimoto** [comment]
Please rename 1PkiDgB5Eg2Ky1bdnDujcMASKWLyeoVn4b 
to "TestCluster CDNTEST 0"
