### ISSUE TITLE
zv.anon: every time clicking on any page or reloading while ALREADY logged in with zv.anon, a new certificate is generated again and again

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#64]
![snap 2017-06-29 at 10 16 52](https://user-images.githubusercontent.com/20817185/27678132-640cd240-5cb4-11e7-8ce4-cfb529915f10.png)

**Comment by dnelband** [comment]
tested on 2 locals & the proxies, i cant reproduce, but it sounds like a behaviour of a couple of updates ago, please try to clear cache -
in chrome: toolbar -> view -> developer -> developer tools (i.e inspect element) and then, when the developer console is open, long click on the refresh button until it shows a menu, on that menu choose "empty cache and hard reload"
