### ISSUE TITLE
Add "RSS Feeds" aka "Follow a Topic or Channel"

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#65]

**Comment by dnelband** [comment]
done, there are 3 types of follow: follow new topics, follow channel, follow topics comments.
is the placement / icon / behaviour ok?

**Comment by dnelband** [comment]
ok one thing i noticed - on the feed, the text of the post is filled with the html tags (<p>,<br/>, etc'). a solution to this, in case it bothers you, can be just to have another attr but with stripped tags, i.e clean text, but it will only be valid on the new topics

**Comment by haschimoto** [comment]
its okay for now
