### ISSUE TITLE
embed video not visible, nor placeholder

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#70]
https://zeronet.maxweiss.io/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?view:topic+topic_id=1JvEtCFJrYcLwWut2p9fXyLidLbzptHaTBtopic2

**Comment by haschimoto** [comment]
also on other proxies only looks like this:
![snap 2017-08-09 at 17 28 20](https://user-images.githubusercontent.com/20817185/29129771-2f3e4f28-7d28-11e7-8b3d-e1c7f47ff345.png)

**Comment by dnelband** [comment]
it seems that peers with an older version of the DB dont see it, new peers / peers with updated db schema do. i'm trying to figure out why it doesnt update automatically on some peers / proxies
