### ISSUE TITLE
voting and commenting throws error?

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#75]
![snap 2017-09-06 at 21 44 14](https://user-images.githubusercontent.com/20817185/30131300-8bcef186-934c-11e7-8ab6-48be0d62d1a5.png)

**Comment by dnelband** [comment]
this error msg appears when users performs any kind of action if his content.json is not updated to run with the latest zeronet update. although it shows error, it still posts, and after the first time you see it the content.json is then fixed. can you test again if it works?

**Comment by haschimoto** [comment]
it keeps throwing this error message, so content.json is not fixed then after first time?
