### ISSUE TITLE
img doesnt work anymnore?

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#87]
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=topic+id=1R67TfYzNkCnh89EFfGmXn5LMb4hXaMRQ4

**Comment by haschimoto** [comment]
this looks especially bad:
![snap 2018-02-05 at 18 27 11](https://user-images.githubusercontent.com/20817185/35819174-3e68264c-0aa2-11e8-86d6-a63a5dba84c4.png)

**Comment by haschimoto** [comment]
only after 4xtimes hitting "Reload" it  came up with the img:
![snap 2018-02-05 at 18 28 16](https://user-images.githubusercontent.com/20817185/35819256-6c1c31a0-0aa2-11e8-80e7-e504f382f152.png)

**Comment by dnelband** [comment]
i've added a loading overlay (the question mark image), about the loading speed of images load / file download there should be no difference , that goes through the zero api the same way as before
