### ISSUE TITLE
page 13: DOGE is an img, but doesnt appüear it is as in list view IMG!

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#89]
![snap 2018-02-05 at 18 32 08](https://user-images.githubusercontent.com/20817185/35819421-f8c615a8-0aa2-11e8-9167-981532aa713f.png)

**Comment by haschimoto** [comment]
where is it??????
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=topic+id=1DobcNU81BZrQViu9L6uUu7qcC4Afd9r962

**Comment by dnelband** [comment]
this was an old topic before some changes were made (we had a similar issue in june), i've added a workaround fix for older topics to find their files

**Comment by haschimoto** [comment]
Lets please remove the zerovoat placeholder and display the img placeholder there.

If there is no img or link or video as main attachement, lets not show anything there, please make it just empty space the size of a real placeholder.
