### ISSUE TITLE
List view: use generic img for VIDEO posts as in initial comment

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#90]
now its broken img....
![snap 2018-02-05 at 18 34 57](https://user-images.githubusercontent.com/20817185/35819567-5e888f88-0aa3-11e8-8341-d5a19c2a5d5b.png)

**Comment by dnelband** [comment]
for some reason, the ifs logo i wanted to use for embeded files was not signed in the content json, no matter what i tries. i've changed it so embeded files will just behave like regular files now (i.e video icon, image display etc'). is this find like this, or should i change the video icon to the ZeroVoat logo?

**Comment by haschimoto** [comment]
it hsows now, but lets remove all zerologos as in other ticket.
