### ISSUE TITLE
Do not load external linked media files, add overlay placeholder that says "EXTERNAL! LOAD?" in RED

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#93]
e.g. here:
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=topic+id=1BUYfNnKgAaCaq3Qwn1HEaPCyAJWGWWZDttopic1

So then no external content is visible/loaded by default.
Also, on these true internet links, there is no PEER number, but it could read "EXTERNAL" IN RED after being loaded when hovered.

**Comment by dnelband** [comment]
is it good like that? btw i've added a condition to the topic form that embeded links must begin with merged-CDN, should i remove it ? it will be risky cause people can just paste whatever . we can create a check or a preview that validates it

**Comment by haschimoto** [comment]
Imo we should allow any external links, but shield the content from loading
with a placeholder, until the user allows it.

**Comment by haschimoto** [comment]
awesome! is it really only loading when pressed though?

**Comment by haschimoto** [comment]
because otherwise if loaded in the back and just "overlayed" it will reveal info about the user.

**Comment by haschimoto** [comment]
also not yet working with files inside text area:
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=topic+id=1E6q3J9comogQMX5nMUkgN4scofBy1NPuJtopic35

**Comment by dnelband** [comment]
yeah, since its an external link, it will only load when its visible on the DOM (html of the page) and before you click that element does not exist in there

**Comment by dnelband** [comment]
hmm that is more complicated to control, i'll figure something out
