### ISSUE TITLE
cannot post comments

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#95]
When replying, in FF and Windows 7 pressing "Post comment" does nothing.

**Comment by haschimoto** [comment]
also main comment. logged out and in again.

**Comment by haschimoto** [comment]
i saw new version a few minutes ago, updated, but STILL cannot reply to your "Now comments work" comment....

**Comment by haschimoto** [comment]
cant add new comment, cant add new topic, I see all the fields and forms fine, but the BUTTON doesnt work...

**Comment by dnelband** [comment]
it was a test comment on chrome, ignore it, the problem is on firefox, im fixing it now

**Comment by haschimoto** [comment]
thanks

**Comment by haschimoto** [comment]
posting "New Topic" now works, yay!
Still comments cant be tested since that section never finishes loading...
