### ISSUE TITLE
make sort buttons transparent to distinguish between sort and "New Topic"

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#96]
![snap 2018-02-06 at 20 07 43](https://user-images.githubusercontent.com/20817185/35878736-76da73c2-0b79-11e8-934f-8955f2928023.png)

**Comment by dnelband** [comment]
i.e without background? or with just the border?

**Comment by haschimoto** [comment]
Just the border.

**Comment by haschimoto** [comment]
look great!
