### ISSUE TITLE
userheader: missing "comments" icon, should be always visible even if no comments yet

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#97]

**Comment by dnelband** [comment]
ok, i've omitted it since i've added the option to edit comments on the fly. the problem right now is that it loads comments quite slow. i need to optimize the comment load in general.

**Comment by dnelband** [comment]
i've removed the "ready" label because it occures to me that in user comments view the comments should not be nested, and shouldnt be replied also, i'll change it
